apiVersion: v1
kind: ConfigMap
metadata:
  name: lmon-aggregator-config
  namespace: lmon
  labels:
    app.kubernetes.io/name: lmon
    app.kubernetes.io/component: aggregator
data:
  config.yaml: |
    kubernetes:
      enabled: true
      in_cluster: true
    aggregator:
      node_label: "app.kubernetes.io/name=lmon-node"
      node_port: 8080
      node_metrics_path: /metrics
      scrape_interval: 30
    monitoring:
      interval: 30
      k8sevents:
        default:
          namespaces: ""
          threshold: 10
          window: 600
          icon: lightning
      k8snodes:
        cluster:
          icon: hdd-rack
      system:
        cpu:
          threshold: 90
          icon: cpu
        memory:
          threshold: 90
          icon: speedometer
        title: "lmon Aggregator"
    web:
      host: 0.0.0.0
      port: 8080
    webhook:
      enabled: false
