apiVersion: v1
kind: ConfigMap
metadata:
  name: lmon-node-config
  namespace: lmon
  labels:
    app.kubernetes.io/name: lmon
    app.kubernetes.io/component: node
data:
  config.yaml: |
    monitoring:
      interval: 30
      disk:
        root:
          path: /hostroot
          threshold: 80
          icon: hdd
        var:
          path: /hostroot/var
          threshold: 85
          icon: hdd
      system:
        cpu:
          threshold: 90
          icon: cpu
        memory:
          threshold: 90
          icon: speedometer
        title: "lmon Node Agent"
    web:
      host: 0.0.0.0
      port: 8080
    webhook:
      enabled: false
