monitoring:
    interval: 60
    disk:
        - path: /
          threshold: 80
          icon: storage
    system:
        cputhreshold: 80
        memorythreshold: 80
        cpuicon: memory
        memoryicon: memory
    healthchecks: []
web:
    host: updated-host
    port: 9090
webhook:
    enabled: false
    url: ""
